package com.brokenhuskysledteam.spacetradersio.sdk.api.mapper

import com.brokenhuskysledteam.spacetradersio.sdk.api.dto.ErrorBodyDto
import com.brokenhuskysledteam.spacetradersio.sdk.domain.model.SpaceTradersError

fun ErrorBodyDto.toDomain(): SpaceTradersError {
    return when (code) {
        // General errors (3000-3200)
        3000 -> SpaceTradersError.GeneralError.ResponseSerialization(code, message, data)
        3001 -> SpaceTradersError.GeneralError.UnprocessableInput(code, message, data)
        3002 -> SpaceTradersError.GeneralError.AllErrorHandlersFailed(code, message, data)
        3100 -> SpaceTradersError.GeneralError.SystemStatusMaintenance(code, message, data)
        3200 -> SpaceTradersError.GeneralError.Reset(code, message, data)

        // Cooldown
        4000 -> SpaceTradersError.CooldownConflict(code, message, data)

        // Waypoint access
        4001 -> SpaceTradersError.WaypointNoAccess(code, message, data)

        // Auth errors (4100-4116)
        4100 -> SpaceTradersError.AuthError.TokenEmpty(code, message, data)
        4101 -> SpaceTradersError.AuthError.TokenMissingSubject(code, message, data)
        4102 -> SpaceTradersError.AuthError.TokenInvalidSubject(code, message, data)
        4103 -> SpaceTradersError.AuthError.MissingTokenRequest(code, message, data)
        4104 -> SpaceTradersError.AuthError.InvalidTokenRequest(code, message, data)
        4105 -> SpaceTradersError.AuthError.InvalidTokenSubject(code, message, data)
        4106 -> SpaceTradersError.AuthError.AccountNotExists(code, message, data)
        4107 -> SpaceTradersError.AuthError.AgentNotExists(code, message, data)
        4108 -> SpaceTradersError.AuthError.AccountHasNoAgent(code, message, data)
        4109 -> SpaceTradersError.AuthError.TokenInvalidVersion(code, message, data)
        4110 -> SpaceTradersError.AuthError.RegisterAgentSymbolReserved(code, message, data)
        4111 -> SpaceTradersError.AuthError.RegisterAgentConflictSymbol(code, message, data)
        4112 -> SpaceTradersError.AuthError.RegisterAgentNoStartingLocations(code, message, data)
        4113 -> SpaceTradersError.AuthError.TokenResetDateMismatch(code, message, data)
        4114 -> SpaceTradersError.AuthError.InvalidAccountRole(code, message, data)
        4115 -> SpaceTradersError.AuthError.InvalidToken(code, message, data)
        4116 -> SpaceTradersError.AuthError.MissingAccountTokenRequest(code, message, data)

        // Navigation errors (4200-4204)
        4200 -> SpaceTradersError.NavigationError.InTransit(code, message, data)
        4201 -> SpaceTradersError.NavigationError.InvalidDestination(code, message, data)
        4202 -> SpaceTradersError.NavigationError.OutsideSystem(code, message, data)
        4203 -> SpaceTradersError.NavigationError.InsufficientFuel(code, message, data)
        4204 -> SpaceTradersError.NavigationError.SameDestination(code, message, data)

        // Ship operation errors (4205-4271)
        4205 -> SpaceTradersError.ShipOperationError.ExtractInvalidWaypoint(code, message, data)
        4206 -> SpaceTradersError.ShipOperationError.ExtractPermission(code, message, data)
        4214 -> SpaceTradersError.ShipOperationError.InTransit(code, message, data)
        4215 -> SpaceTradersError.ShipOperationError.MissingSensorArrays(code, message, data)
        4216 -> SpaceTradersError.ShipOperationError.PurchaseCredits(code, message, data)
        4217 -> SpaceTradersError.ShipOperationError.CargoExceedsLimit(code, message, data)
        4218 -> SpaceTradersError.ShipOperationError.CargoMissing(code, message, data)
        4219 -> SpaceTradersError.ShipOperationError.CargoUnitCount(code, message, data)
        4220 -> SpaceTradersError.ShipOperationError.SurveyVerification(code, message, data)
        4221 -> SpaceTradersError.ShipOperationError.SurveyExpiration(code, message, data)
        4222 -> SpaceTradersError.ShipOperationError.SurveyWaypointType(code, message, data)
        4223 -> SpaceTradersError.ShipOperationError.SurveyOrbit(code, message, data)
        4224 -> SpaceTradersError.ShipOperationError.SurveyExhausted(code, message, data)
        4228 -> SpaceTradersError.ShipOperationError.CargoFull(code, message, data)
        4230 -> SpaceTradersError.ShipOperationError.WaypointCharted(code, message, data)
        4231 -> SpaceTradersError.ShipOperationError.TransferShipNotFound(code, message, data)
        4232 -> SpaceTradersError.ShipOperationError.TransferAgentConflict(code, message, data)
        4233 -> SpaceTradersError.ShipOperationError.TransferSameShipConflict(code, message, data)
        4234 -> SpaceTradersError.ShipOperationError.TransferLocationConflict(code, message, data)
        4235 -> SpaceTradersError.ShipOperationError.WarpInsideSystem(code, message, data)
        4236 -> SpaceTradersError.ShipOperationError.NotInOrbit(code, message, data)
        4237 -> SpaceTradersError.ShipOperationError.InvalidRefineryGood(code, message, data)
        4238 -> SpaceTradersError.ShipOperationError.InvalidRefineryType(code, message, data)
        4239 -> SpaceTradersError.ShipOperationError.MissingRefinery(code, message, data)
        4240 -> SpaceTradersError.ShipOperationError.MissingSurveyor(code, message, data)
        4241 -> SpaceTradersError.ShipOperationError.MissingWarpDrive(code, message, data)
        4242 -> SpaceTradersError.ShipOperationError.MissingMineralProcessor(code, message, data)
        4243 -> SpaceTradersError.ShipOperationError.MissingMiningLasers(code, message, data)
        4244 -> SpaceTradersError.ShipOperationError.NotDocked(code, message, data)
        4245 -> SpaceTradersError.ShipOperationError.PurchaseNotPresent(code, message, data)
        4246 -> SpaceTradersError.ShipOperationError.MountNoShipyard(code, message, data)
        4247 -> SpaceTradersError.ShipOperationError.MissingMount(code, message, data)
        4248 -> SpaceTradersError.ShipOperationError.MountInsufficientCredits(code, message, data)
        4249 -> SpaceTradersError.ShipOperationError.MissingPower(code, message, data)
        4250 -> SpaceTradersError.ShipOperationError.MissingSlots(code, message, data)
        4251 -> SpaceTradersError.ShipOperationError.MissingMounts(code, message, data)
        4252 -> SpaceTradersError.ShipOperationError.MissingCrew(code, message, data)
        4253 -> SpaceTradersError.ShipOperationError.ExtractDestabilized(code, message, data)
        4254 -> SpaceTradersError.ShipOperationError.JumpInvalidOrigin(code, message, data)
        4255 -> SpaceTradersError.ShipOperationError.JumpInvalidWaypoint(code, message, data)
        4256 -> SpaceTradersError.ShipOperationError.JumpOriginUnderConstruction(code, message, data)
        4257 -> SpaceTradersError.ShipOperationError.MissingGasProcessor(code, message, data)
        4258 -> SpaceTradersError.ShipOperationError.MissingGasSiphons(code, message, data)
        4259 -> SpaceTradersError.ShipOperationError.SiphonInvalidWaypoint(code, message, data)
        4260 -> SpaceTradersError.ShipOperationError.SiphonPermission(code, message, data)
        4261 -> SpaceTradersError.ShipOperationError.WaypointNoYield(code, message, data)
        4262 -> SpaceTradersError.ShipOperationError.JumpDestinationUnderConstruction(code, message, data)
        4263 -> SpaceTradersError.ShipOperationError.ScrapInvalidTrait(code, message, data)
        4264 -> SpaceTradersError.ShipOperationError.RepairInvalidTrait(code, message, data)
        4265 -> SpaceTradersError.ShipOperationError.AgentInsufficientCredits(code, message, data)
        4266 -> SpaceTradersError.ShipOperationError.ModuleNoShipyard(code, message, data)
        4267 -> SpaceTradersError.ShipOperationError.ModuleNotInstalled(code, message, data)
        4268 -> SpaceTradersError.ShipOperationError.ModuleInsufficientCredits(code, message, data)
        4269 -> SpaceTradersError.ShipOperationError.CantSlowDownWhileInTransit(code, message, data)
        4270 -> SpaceTradersError.ShipOperationError.ExtractInvalidSurveyLocation(code, message, data)
        4271 -> SpaceTradersError.ShipOperationError.TransferDockedOrbitConflict(code, message, data)

        // Contract errors (4500-4511)
        4500 -> SpaceTradersError.ContractError.AcceptNotAuthorized(code, message, data)
        4501 -> SpaceTradersError.ContractError.AcceptConflict(code, message, data)
        4502 -> SpaceTradersError.ContractError.FulfillDelivery(code, message, data)
        4503 -> SpaceTradersError.ContractError.Deadline(code, message, data)
        4504 -> SpaceTradersError.ContractError.Fulfilled(code, message, data)
        4505 -> SpaceTradersError.ContractError.NotAccepted(code, message, data)
        4506 -> SpaceTradersError.ContractError.NotAuthorized(code, message, data)
        4508 -> SpaceTradersError.ContractError.ShipDeliverTerms(code, message, data)
        4509 -> SpaceTradersError.ContractError.ShipDeliverFulfilled(code, message, data)
        4510 -> SpaceTradersError.ContractError.ShipDeliverInvalidLocation(code, message, data)
        4511 -> SpaceTradersError.ContractError.ExistingContract(code, message, data)

        // Market errors (4600-4605)
        4600 -> SpaceTradersError.MarketError.TradeInsufficientCredits(code, message, data)
        4601 -> SpaceTradersError.MarketError.TradeNoPurchase(code, message, data)
        4602 -> SpaceTradersError.MarketError.TradeNotSold(code, message, data)
        4604 -> SpaceTradersError.MarketError.TradeUnitLimit(code, message, data)
        4605 -> SpaceTradersError.MarketError.ShipNotAvailableForPurchase(code, message, data)

        // Waypoint faction
        4700 -> SpaceTradersError.WaypointNoFaction(code, message, data)

        // Construction errors (4800-4802)
        4800 -> SpaceTradersError.ConstructionError.MaterialNotRequired(code, message, data)
        4801 -> SpaceTradersError.ConstructionError.MaterialFulfilled(code, message, data)
        4802 -> SpaceTradersError.ConstructionError.ShipInvalidLocation(code, message, data)

        // Media type
        5000 -> SpaceTradersError.UnsupportedMediaType(code, message, data)

        // Unrecognized codes
        else -> SpaceTradersError.Unknown(code, message, data)
    }
}
