package com.brokenhuskysledteam.spacetradersio.sdk.data.db

import android.content.Context
import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.driver.android.AndroidSqliteDriver

/**
 * Android implementation of the [SqlDriverFactory] `expect` class declared in `commonMain`.
 *
 * **Pattern:** `actual class` with platform-specific constructor. The Android target
 * requires an `android.content.Context` to locate the application's sandboxed storage
 * directory — this is where Android physically places the SQLite database file. The
 * `expect` class in `commonMain` has no constructor parameters, so `commonMain` code
 * that receives a pre-built `SqlDriverFactory` instance can call [create] uniformly
 * without knowing about `Context`. The `Context` dependency is resolved at the DI
 * layer (Hilt) before the factory reaches shared code.
 *
 * **SQLDelight multiplatform value:** The `.sq` schema files and the generated
 * `SpaceTradersDatabase` / `AgentQueries` / `ShipQueries` interfaces are 100%
 * shared across platforms. Only the driver (this file on Android, `SqlDriverFactory.ios.kt`
 * on iOS) differs. Switching databases or upgrading SQLDelight affects a single file
 * per platform rather than every query site.
 *
 * **In this project:** Constructed by the Hilt `SdkModule` and injected wherever the
 * database needs to be initialized. A single [SpaceTradersDatabase] instance is
 * created from the returned [SqlDriver] and shared across all repositories.
 *
 * @param context The Android application context used to resolve the database file
 *   path. Pass the application context (not an activity context) to avoid leaks.
 */
actual class SqlDriverFactory(private val context: Context) {

    /**
     * Creates an [AndroidSqliteDriver] backed by the app's private SQLite storage.
     *
     * [SpaceTradersDatabase.Schema] is generated by SQLDelight from the `.sq` files
     * and carries the current schema version plus the `create` / `migrate` callbacks
     * that SQLDelight calls automatically when the database is first opened or needs
     * upgrading. The filename `"spacetraders.db"` must match the value used in
     * [SqlDriverFactory.ios] so that the same logical database name is used on both
     * platforms.
     *
     * @return A ready-to-use [SqlDriver] connected to `spacetraders.db` in the app's
     *   private data directory.
     */
    actual fun create(): SqlDriver =
        AndroidSqliteDriver(SpaceTradersDatabase.Schema, context, "spacetraders.db")
}
